# Entrada e saída de dados

Este notebook conterá nossas referências sobre entrada e saída de dados. O pandas pode ler uma variedade de tipos de arquivos usando seus métodos pd.read_. Vejamos os tipos de dados mais comuns:

In [2]:
# Instale um pacote pip no kernel atual do Jupyter 
import  sys 
!{ sys.executable } -m pip install numpy

Requirement already satisfied: numpy in c:\users\glauc\anaconda3\lib\site-packages (1.21.5)

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.array([1,2,3])

array([1, 2, 3])

## CSV

### CSV Input

In [3]:
df = pd.read_csv('exemplo.csv')
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### Saída de dados tipo CSV

In [4]:
df.to_csv('exemplo.csv',index=False)

## Excel

Pandas podem ler e escrever arquivos do Excel, tenha em mente, isso só importa dados. Não fórmulas nem imagens, lembrando que imagens ou macros podem bugar o método.

### Entrada via Excel

In [5]:
pd.read_excel('Exemplo_Excel.xlsx',sheet_name='Sheet1')

   index   a   b   c   d
0      0   0   1   2   3
1      1   4   5   6   7
2      2   8   9  10  11
3      3  12  13  14  15

### Saída via Excel

In [6]:
df.to_excel('Exemplo_Excel_Saida.xlsx',sheet_name='Sheet1')

## HTML

Você pode precisar instalar htmllib5, lxml e BeautifulSoup4. No seu terminal / prompt de comando, execute:

    conda install lxml
    conda install html5lib
    conda install BeautifulSoup4
    
Em seguida, reinicie o Jupyter Notebook. 
(Ou use instalação de pip se não estiver usando a Distribuição de Anaconda)
Pandas podem ler guias de tabelas fora de html. Por exemplo:

In [12]:
#conda install lxml

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 24.3.0

Please update conda by running

    $ conda update -n base -c defaults conda

In [13]:
conda install html5lib

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: c:\Users\glauc\anaconda3

  added / updated specs:
    - html5lib


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    html5lib-1.1               |     pyhd3eb1b0_0          91 KB
    ------------------------------------------------------------
                                           Total:          91 KB

The following NEW packages will be INSTALLED:

  html5lib           pkgs/main/noarch::html5lib-1.1-pyhd3eb1b0_0



Downloading and Extracting Packages

html5lib-1.1         | 91 KB     |            |   0%
html5lib-1.1         | 91 KB     | ########## | 100%
html5lib-1.1         | 91 KB     | ########## | 100%
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 24.3.0

Please update conda by running

    $ conda update -n base -c defaults conda

In [14]:
conda install BeautifulSoup4

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 24.3.0

Please update conda by running

    $ conda update -n base -c defaults conda

In [16]:
conda update -n base -c defaults conda

Collecting package metadata (current_repodata.json): ...working... done
Note: you may need to restart the kernel to use updated packages.
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\glauc\anaconda3

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-pack-0.7.1           |   py39haa95532_0          73 KB
    conda-package-handling-2.2.0|   py39haa95532_0         287 KB
    conda-package-streaming-0.9.0|   py39haa95532_0          29 KB
    pyjwt-2.4.0                |   py39haa95532_0          38 KB
    zstandard-0.19.0           |   py39h2bbff1b_0         340 KB
    ------------------------------------------------------------
                                           Total:         766 KB

The following NEW packages will be INSTALLED:

  conda-package-str~ pkgs/main/win-64::conda-package-streaming-0.9.0-py39haa95532_0
  zstandard          pkgs/main/win-64::zstandard-0.19.0-py39h2bbff1b_0

The following packages will be UPDATED:

  conda-pack         pkgs/main/noarch::conda-pack-0.6.0-py~ --> pkgs/main/win-64::conda-pack-0.7.1-py39haa95532_0
  conda-package-han~                   1.8.1-py39h8cc25b3_0 --> 2.2.0-py39haa95532_0
  pyjwt                                2.1.0-py39haa95532_0 --> 2.4.0-py39haa95532_0



Downloading and Extracting Packages

pyjwt-2.4.0          | 38 KB     |            |   0%
pyjwt-2.4.0          | 38 KB     | ####2      |  42%
pyjwt-2.4.0          | 38 KB     | ########## | 100%
pyjwt-2.4.0          | 38 KB     | ########## | 100%

zstandard-0.19.0     | 340 KB    |            |   0%
zstandard-0.19.0     | 340 KB    | ########## | 100%
zstandard-0.19.0     | 340 KB    | ########## | 100%

conda-pack-0.7.1     | 73 KB     |            |   0%
conda-pack-0.7.1     | 73 KB     | ########## | 100%
conda-pack-0.7.1     | 73 KB     | ########## | 100%

conda-package-stream | 29 KB     |            |   0%
conda-package-stream | 29 KB     | ########## | 100%

conda-package-handli | 287 KB    |            |   0%
conda-package-handli | 287 KB    | ########## | 100%
conda-package-handli | 287 KB    | ########## | 100%

==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 24.3.0

Please update conda by running

    $ conda update -n base -c defaults conda

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

### Entrada HTML

A função Pandas read_html irá ler tabelas fora de uma página da Web e retornar uma lista de objetos DataFrame:

In [12]:
df = pd.read_html('https://www.runnersworld.com/races-places/a20823734/these-are-the-worlds-fastest-marathoners-and-marathon-courses/')

In [13]:
df[0]

                             0            1          2               3
0                       Runner  Finish Time  Pace/Mile        Marathon
1        Kelvin Kiptum (Kenya)      2:00:35     4:36.0   Chicago, 2023
2       Eliud Kipchoge (Kenya)      2:01:09     4:37.2    Berlin, 2022
3   Kenenisa Bekele (Ethiopia)      2:01:41     4:38.5    Berlin, 2019
4       Sisay Lemma (Ethiopia)      2:01:48     4:38.7  Valencia, 2023
5       Benson Kipruto (Kenya)      2:02:16     4:39.8     Tokyo, 2024
6    Birhanu Legese (Ethiopia)      2:02:48     4:41.0    Berlin, 2019
7   Mosinet Geremew (Ethiopia)      2:02:55     4:41.3    London, 2019
8     Timothy Kiplagat (Kenya)      2:02:55     4:41.3     Tokyo, 2024
9       Dennis Kimetto (Kenya)      2:02:57     4:41.4    Berlin, 2014
10        Evans Chebet (Kenya)      2:03:00     4:41.5  Valencia, 2020

____